### ISSUE TITLE
Знайти фото корабля

### ISSUE THREAD

**Issue by Khomanchuk** [Khomanchuk/PR4#1]
Знайти найкраще фото в Інтернеті

**Comment by OliynykM** [comment]
В пошуку

**Comment by OliynykM** [comment]
![image](https://user-images.githubusercontent.com/94035639/141069167-55242f77-90fa-430c-a6ad-bb34c99914e1.png)

**Comment by OliynykM** [comment]
Фото корабля знайдено

**Comment by OliynykM** [comment]
Роботу завершив
